---
- hosts: ws
  become: 1
  gather_facts: 1
  ignore_errors: true
  vars:
    user_name: farelle24
    group: terraform
  vars_files:
    - variables.yml

  tasks:
    - name: check server uptime
      command: "{{my_command}}"
      register: uptime_output
    - name: list directory
      shell: ls
    - name: check the kernel version
      command: uname -r 
      register: kernel_output 
    - name: create user
      user:
        name: "{{user_name}}"
    - name: creat group
      group:
        name: "{{group}}"   
    - name: read data
      debug: 
       var: uptime_output.stdout[:19]
    - name: read data
      debug:
        var: kernel_output.stdout   