---
- hosts: ws
  become: yes
  gather_facts: yes
  ignore_errors: true
  tasks:
    - name: Install required packages
      yum:
        name:
          - lsof
          - wget
          - passwd
          - docker
          - unzip
          - java-11
        state: present  

    - name: Create directory 
      file:
        path: /opt/qa/spg
        state: directory  
        
    - name: Create log file 
      file:
        path: /opt/qa/spg/spg.log
        state: touch 

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
